//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.zts;
import com.yahoo.rdl.*;

//
// RoleCertificate - RoleCertificate - a role certificate
//
public class RoleCertificate {
    public String x509Certificate;

    public RoleCertificate setX509Certificate(String x509Certificate) {
        this.x509Certificate = x509Certificate;
        return this;
    }
    public String getX509Certificate() {
        return x509Certificate;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != RoleCertificate.class) {
                return false;
            }
            RoleCertificate a = (RoleCertificate) another;
            if (x509Certificate == null ? a.x509Certificate != null : !x509Certificate.equals(a.x509Certificate)) {
                return false;
            }
        }
        return true;
    }
}
